(define (problem p03) (:domain bat)
(:objects a b c d e f - guy i1 i2 i3 i4 - island)

(:init
    (at a i1)
    (at b i1)
    (at c i1)
    (at d i1)
    (at e i1)
    (at f i1)
    (has-torch a)
    (has-torch f)
    (connected i1 i2)
    (connected i2 i1)
    (connected i2 i3)
    (connected i3 i2)
    (connected i2 i4)
    (connected i4 i2)
    (greater f a) (greater f b) (greater f c) (greater f d) (greater f e) (greater f f)
    (greater e a) (greater e b) (greater e c) (greater e d) (greater e e)
    (greater d a) (greater d b) (greater d c) (greater d d)
    (greater c a) (greater c b) (greater c c)
    (greater b a) (greater b b) 
    (greater a a)
    (= (guy-cost a) 1)
    (= (guy-cost b) 2)
    (= (guy-cost c) 3)
    (= (guy-cost d) 4)
    (= (guy-cost e) 5)
    (= (guy-cost f) 6)
)

(:goal (and
    (at a i3) (at b i3) (at c i3) (at d i4) (at e i4) (at f i4)
))

;un-comment the following line if metric is needed
(:metric minimize (total-cost))
)
